### PR TITLE
Add conflict with pdepend 2.16.0

### PR DESCRIPTION
**Pull request by cilefen**
Type:  bugfix
Breaking change: no
Relates to: https://github.com/pdepend/pdepend/issues/695

pdepend 2.16.0 allows Symfony Framework 7 component compatibility but it is not actually compatible with those components. Prevent installs of that version of pdepend.

### CODE REVIEW

**Comment by AJenbo** [comment]
The issue is not in phpmd

**Comment by cilefen** [comment]
Here is a reproduction `composer.json`:

```
{
    "require": {
        "phpmd/phpmd": "2.14.1"
    }
}
```

It is not possible to use PHPMD at this moment after typing `composer update`. Adding this conflict will prevent the useless version of pdepend from installing.

**Comment by AJenbo** [comment]
You can limit the change of either Symfony or pdepend in your project to avoid the issue. A solution is being worked on in pdepend.

**Comment by AJenbo** [comment]
The issue should now be resolved in pdepend 2.16.1 so simply updating it should resolve the issue.

**Pull request closed without merging**
