### PR TITLE
Remove Class Aliases

### PR DESCRIPTION
**Pull request by ravage84**
Type: refactoring
Issue: Resolves none
Breaking change: yes, see below

These were introduced over 6 years ago in PHPMD 2.0.0-beta1.
Probably as a BC bridge for people migrating from pre PHP 5.3, where there were no namespaces.

https://github.com/phpmd/phpmd/commit/a86a061d2b7e0824512556e8dd2aa1b68528d80a

Even though this _could_ be considered a BC break, I think it is still safe to remove today.

### CODE REVIEW

**Comment by tvbeek** [comment]
I think because it is a possible BC break we should deprecate it. I added it to  #746

**Comment by ravage84** [comment]
@tvbeek & @kylekatarnls I see your points but I'm not sure this is really an issue.

Besides being introduced so long ago, these class aliases are added to the [PHPMD binary](https://github.com/phpmd/phpmd/blob/2.8.2/src/bin/phpmd#L49-L120), not any library related code.

To my understanding, this means that only somebody "extending" (read: relying on) this executable AND using one of these outdated class aliases would be affected.

**Comment by ravage84** [comment]
By the way, the list of aliased classes is incomplete, anyway:

grafik
****

**Comment by ravage84** [comment]
These aliases _could_ be related to the now defunct PEAR installation option.

This can be seen here:
https://github.com/phpmd/phpmd/issues/338
https://github.com/phpmd/phpmd/pull/87
https://github.com/phpmd/phpmd/issues/127
https://github.com/phpmd/phpmd/issues/75
https://github.com/phpmd/phpmd/issues/126
https://github.com/phpmd/phpmd/issues/55

Some other old issues with ``PHPM_PMD*`` namespaces:
https://github.com/phpmd/phpmd/issues/28
https://github.com/phpmd/phpmd/issues/131

A more recent (2017) issue, seemingly not PEAR:
https://github.com/phpmd/phpmd/issues/526

An issue from somebody who uses PHPMD as library (2013):
https://github.com/phpmd/phpmd/issues/72

**Comment by kylekatarnls** [comment]
I never said PHPM_PMD_* is OK nor declined this PR, I just say it needs to be documented, we should help users to deal with this change or at least warn them.

**Comment by ravage84** [comment]
How about we outline it in the change log and the release notes?

> The class aliases ``PHP_PMD_*`` used for PHPMD 1.x backwards PEAR compatibility were removed. If you happen to still depend on these, please adjust your code like so:
> 
> From ``PHP_PMD_[Component]_[Class]'`` to ``PHPMD\[Component]\[Class]``,
> as in ``PHP_PMD_Renderer_HTMLRenderer'`` to ``PHPMD\Renderer\HTMLRenderer``.

Or do you propose a different text?

**Pull request merged**
