### PR TITLE
Add Junit compatible output

### PR DESCRIPTION
**Pull request by jelly**
Add an output format which can be easily used in combination with
Jenkins. The Junit plugin is by default included in Jenkins.

### CODE REVIEW

**Comment by mvmaasakkers** [comment]
👍

**Comment by millerrs** [comment]
+1 This would be a nice feature to have.

**Comment by mvmaasakkers** [comment]
@jelly I opened a PR on your fork to fix the travis build

**Comment by jelly** [comment]
@mvmaasakkers thanks, just merged it!

**Comment by masi** [comment]
+1

AppVeyor seems to fail because it inistalls PHP 7.2 and cannot cd into /tools/php71 later on. So it's not probably not an issue with the code itself.

**Comment by drmmr763** [comment]
Just want to +1 this PR in hopes to get it merged. Wanting to use phpmd in my project but we have a full jenkins pipeline based on JUnit output. For the time being I'm going to look at @jelly's python conversion script.

**Comment by marius-balteanu** [comment]
+1

**Comment by marius-balteanu** [comment]
There is something we can do to have this feature integrated?

**Comment by DAcodedBEAT** [comment]
:+1:'ing this PR.  This would be an amazing feature to have!

**Comment by ravage84** [comment]
As mentioned in https://github.com/phpmd/phpmd/issues/538#issuecomment-505668343, PHPMD has already a working and standardized integration into Jenkins.

Normally, a tool like PHPMD is treated as "metrics tool", which provides various code metrics, not as a "testing tool", which executes tests upon some code.

I'm not against this feature, but PHPStan, for example is such a "testing tool", as its target is to tell you yes, your whole code is good (=pass), or no, not everything is OK (=fail).

Those are two distinct mindsets^and I'm not sure it should be combined into a single tool.

**Comment by tominventisbe** [comment]
@ravage84 I understand your point, especially with regards to rules such as code complexity, which are more of an indicator rather than "you must fix this right now".

There are however some arguments to the contrary:

* PHPMD also offers rules that do fit the "tests" description, such as `EvalExpression`, `CamelCaseClassName`, `ConstructorWithNameAsEnclosingClass`, and so on.
* It's not just Jenkins benefiting from this anymore, Bitbucket pipelines has official support for JUnit files and will show you an overview of problems this way.
* JUnit is traditionally used for actual tests, but it's just a standardized schema for XML documents, so it can be used for almost any type of reporting. It is also one of the few widely supported output formats and getting tools to support new XML schemas or output formats because JUnit was only intended for "real" tests"would be a painful process - one could also similarly argue that "we should not be using JUnit XML for anything in PHP because it was originally intended for JUnit in Java only".

Now that PHPMD has support for both minimum and maximum priority setting, we are using PHPMD both as testing and metrics tool in our pipelines. We use priority 1 for actual tests in JUnit format that should fail CI and use other priorities for things such as warnings and information, which will not fail CI.

Granted, it would be more convenient if there was a separation between errors and warnings so editors or IDEs could also make the differentiation instead of having to run PHPMD with different priorities multiple times, but that is a different problem 😄.

**Comment by kylekatarnls** [comment]
> PHPMD also offers rules that do fit the "tests" description, such as EvalExpression, CamelCaseClassName, ConstructorWithNameAsEnclosingClass, and so on.

Not necessarily. It's as other rules some: "Watch this, maybe it's a mistake." but not absolute constraints:

`EvalExpression`: you may actually need `eval()` with no alternative for some needs, and you may perfectly handle those `eval()` calls in a way that causes no risk.

`CamelCaseClassName`: you may need to keep classes with other lowerCase/Snake_Case for backward-compatibility reason.

`ConstructorWithNameAsEnclosingClass`: Same as above, you may need one for backward-compatibility.

So I would say none of the PHPMD rule are an absolute mandatory requirement until you evaluate than you project has no reason to break the chosen rules so you can use those rules as requirement, but the warning/error level of each rule is a project-specific consideration. PHPMD may provide a way to choose levels for rule, but I don't think we should decide a default level for each rule.

We may also consider opening the report option to custom ones, something like:

```shell
phpmd /path/to/source file:/path/to/my-custom-renderer.php codesize
```

**Comment by tominventisbe** [comment]
@kylekatarnls Agreed. It is indeed a project-specific concern in that some projects may consider these rules indicators and others errors, but this is not necessarily PHPMD's problem.

Custom reporting would also work if a plugin package could be provided that adds support for JUnit formatting. Currently, one has to make a fork that merges in this pull request until the problem is solved (though if this pull request were rebased, one could probably target the branch directly for now).

**Comment by ravage84** [comment]
Since this feature is kinda popular and since JUnit is a quite widespeard format, I'm OK with merging this, if we can get it to the necessary quality level (documentation & tests).

@jelly and/or @tominventisbe are you willing to put energy into this?

**Comment by tominventisbe** [comment]
@ravage84 Unfortunately, I cannot currently promise to commit time to this. This doesn't mean I won't ever be able to to, but I can't guarantee it at the moment.

May sound like a bit of a useless comment, but I didn't want to fade away into the void and leave you with no response 😄.

**Comment by kylekatarnls** [comment]
Hi @tominventisbe, no worry, it can be postponed. If someone else want to be assigned to this, we will assign him/her. Meanwhile as the core team is a bit busy (and bugs have the priority over new features), we will assume we'll wait for your changes.

Thanks.

**Comment by ravage84** [comment]
@jelly or @tominventisbe are you still interested in pursuing this?

**Comment by tominventisbe** [comment]
@ravage84 I still think it would be of benefit to this project, but I'm not optimistic about getting company time allocated for it in the near future, unfortunately :neutral_face: .

**Comment by jelly** [comment]
> @jelly or @tominventisbe are you still interested in pursuing this?

I'm long phpmd in this configuration, so I'm not interested anymore, sorry.

**Comment by XavierChevalier** [comment]
What is the progress of this pull request?

**Comment by davidverholen** [comment]
What would be needed for this to be merged? only the test coverage for input / expected output?
This would be a great addition, in our case to be able to integrate phpmd with the gitlab reports feature

**Comment by kylekatarnls** [comment]
> What would be needed for this to be merged? only the test coverage for input / expected output?
> This would be a great addition, in our case to be able to integrate phpmd with the gitlab reports feature

As you can see in the PR status and labels:
- unit tests
- documentation
- fixing conflict

As we're already overwhelmed in this project, the priority goes on fully-compliant pull-requests, and our development efforts is put in fixes and compatibility with supported tools over supporting new tools.

**Comment by sjinks** [comment]
In case this helps anybody, here the XSL stylesheet that can be used to transform phpmd's XML output into JUnit format (I tried to make it compatible with [this XML Schema](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd))

```xsl
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="xml" indent="yes" encoding="utf-8"/>

    <xsl:template match="/pmd">
        <testsuites failures="{count(./file/violation)}" errors="{count(./error)}">
            <xsl:apply-templates select="file" />
            <xsl:apply-templates select="error" />
        </testsuites>
    </xsl:template>

    <xsl:template match="/pmd/file">
        <testsuite name="{@name}" tests="{count(./violation)}" failures="{count(./violation)}" errors="0">
            <xsl:apply-templates select="violation" />
        </testsuite>
    </xsl:template>

    <xsl:template match="/pmd/error">
        <testsuite name="{@name}" tests="1" failures="0" errors="1">
            <testcase name="error">
                <error message="{@msg}" type="error">
                    <xsl:value-of select="@msg" />
                </error>
            </testcase>
        </testsuite>
    </xsl:template>

    <xsl:template match="/pmd/file/violation">
        <testcase name="{@rule}">
            <failure message="{normalize-space(text())}" type="{@ruleset}">
                <xsl:value-of select="normalize-space(text())" />
                <xsl:text>&#x0A;</xsl:text>
                <xsl:text>Lines: </xsl:text>
                <xsl:value-of select="@beginline" />
                <xsl:text>-</xsl:text>
                <xsl:value-of select="@endline" />
                <xsl:text>&#x0A;</xsl:text>
                <xsl:value-of select="@externalInfoUrl" />
            </failure>
        </testcase>
    </xsl:template>
</xsl:stylesheet>
```

Sample usage:

```bash
phpmd src xml cleancode | xsltproc junit.xslt -
```

`xsltproc` comes from the `xsltproc` package on the Debian-based systems and `libxslt` on Alpine and CentOS.

**Comment by kylekatarnls** [comment]
Thank you @sjinks (and @gboissinot and @nfalco79 for this config file), we'll mention your solution in our documentation #879 which is the correct path IMO.

Still if @jelly or someone else want to add tests and documentation we'll be able to merge this and support natively this format.

But our core team will not handle this to focus on bug fixes and support new PHP syntaxes over adding features. Thank you all for your help bringing more output compatibility.

**Comment by langemol** [comment]
When I tried using the xslt in gitlab CI, half the fields in the report in the merge request were empty. So I slightly changed the xslt and added some properties based on some phpunit test reports.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="xml" indent="yes" encoding="utf-8"/>

    <xsl:template match="/pmd">
        <testsuites failures="{count(./file/violation)}" errors="{count(./error)}">
            <xsl:apply-templates select="file" />
            <xsl:apply-templates select="error" />
        </testsuites>
    </xsl:template>

    <xsl:template match="/pmd/file">
        <testsuite name="{./violation[1]/@class}" file="{@name}" tests="{count(./violation)}" failures="{count(./violation)}" errors="0">
            <xsl:apply-templates select="violation" />
        </testsuite>
    </xsl:template>

    <xsl:template match="/pmd/error">
        <testsuite name="{@name}" tests="1" failures="0" errors="1">
            <testcase name="error">
                <failure message="{@msg}" type="error">
                    <xsl:value-of select="@msg" />
                </failure>
            </testcase>
        </testsuite>
    </xsl:template>

    <xsl:template match="/pmd/file/violation">
        <testcase name="{@rule}" class="{@class}" classname="{@class}" file="{../@name}" Line="{@beginline}">
            <failure message="{normalize-space(text())}" type="{@ruleset}">
                <xsl:value-of select="normalize-space(text())" />
                <xsl:text>&#x0A;</xsl:text>
                <xsl:text>Category: </xsl:text>
                <xsl:value-of select="@ruleset" />
                <xsl:text> - </xsl:text>
                <xsl:value-of select="@externalInfoUrl" />
                <xsl:text>&#x0A;</xsl:text>
                <xsl:text>File: </xsl:text>
                <xsl:value-of select="../@name" />
                <xsl:text>&#x0A;</xsl:text>
                <xsl:text>Line: </xsl:text>
                <xsl:value-of select="@beginline" />
                <xsl:text>-</xsl:text>
                <xsl:value-of select="@endline" />
                <xsl:text>&#x0A;</xsl:text>
            </failure>
        </testcase>
    </xsl:template>
</xsl:stylesheet>
````

**Pull request closed without merging**
