### PR TITLE
Replace Travis build notification from IRC to the new Gitter core channel

### PR DESCRIPTION
**Pull request by ravage84**
The documentation for the integration read:

````
Instructions

You need to configure your Travis job to send Webhook notifications [https://docs.travis-ci.com/user/notifications].

Add the following to your .travis.yml configuration:

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

Your unique webhook url for this service:

https://webhooks.gitter.im/e/5a993c0b870b2fa9141e
````

### CODE REVIEW

**Comment by MarkVaughn** [comment]
Looks good, this does not run on all PRs does it?

**Comment by ravage84** [comment]
I'm not sure this actually works, as our core channel is "invite-only" but I haven't found any info about that in their documetnation, yet. May be we will need to get in touch with their support team.

**Comment by tvbeek** [comment]
I found it a good idea to test, else we need to change the channel to phpmd.

**Comment by tvbeek** [comment]
afbeelding
It does work 😃

**Comment by ravage84** [comment]
@tvbeek thank you so much for letting us know. I minimized that pane of the UI, so I couldn't see: :smile:

**Pull request merged**
