### PR TITLE
Fix warning/error when trying to export to a non-existing path

### PR DESCRIPTION
**Pull request by jaymoulin**

### CODE REVIEW

**Comment by ravage84** [comment]
@jaymoulin can you explain me a bit more about the issue? A test would be even better. Thanks

**Comment by jaymoulin** [comment]
when you try to export your report in a non existing full path, an error occurs due to the fopen without folder check. StreamWriter already do this check and will fix this case:
ex : 

`/path/to/export` does not exists but `/path` exists. Without the PR, i'm not able to export to `/path/to/export` without manually creating the full path. With the PR, the path will be generated as expected.

**Comment by ravage84** [comment]
Tanks for getting back to me so fast @jaymoulin 

>  StreamWriter already do this check

Do you have some documentation on this? Do you know if the function works the same through all versions of PHP?

A small test would be very helpful, so I can merge with confidence...

**Comment by jaymoulin** [comment]
You already have this test and the documentation since StreamWriter is a PHPMD class ;)
`src/main/php/PHPMD/Writer/StreamWriter.php`

**Comment by ravage84** [comment]
Stupid me, I was loooking at this class always thinking it was some kind of Spl class... 🤣

**Comment by ravage84** [comment]
Thanks!

**Pull request merged**
