### PR TITLE
Update pdepend

### LINKED ISSUE #355: not working with pdepend/pdepend 2.0.0
In composer.json file version `~2.0` is required.
But in 2.0.0 version fo pdepend there is `symfony/dependency-injection` required with only `@stable` version, which could be installed as 2.0.0, with does not have used class:

```
vagrant@fp:/vagrant$ vendor/bin/phpmd file.php text phpmd.xml
PHP Fatal error:  Class 'Symfony\Component\DependencyInjection\Extension\Extension' not found in /vagrant/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/PdependExtension.php on line 58
```

Please, bump pdepend to at least `^2.0.4`, whey they start to rely on `symfony/dependency-injection:^2.4`

### PR DESCRIPTION
**Pull request by keradus**
Fixes #355

### CODE REVIEW

**Comment by ravage84** [comment]
I guess commit https://github.com/pdepend/pdepend/commit/c9085ee5667466f5ac5a774dfc17e7befda86495#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 solved the problem.

Using the caret ``^`` operator is better, too.

Thanks!

**Comment by keradus** [comment]
Exactly.
Thank you for quick response!

Any chances for 2.4.3 release with this fix?

**Comment by ravage84** [comment]
@manuelpichler do you see any obstacle for releasing a 2.4.3 (except for your precious time of course)? It would be a tiny release, though.

**Comment by keradus** [comment]
Any news ? :)

**Pull request merged**
