### PR TITLE
Allow-underscore implemented for Controversial-Rule: CamelCaseVariableName

### PR DESCRIPTION
**Pull request by silentx1981**

### CODE REVIEW

**Comment by ravage84** [comment]
Hi @silentx1981 thanks for the PR.
Could you add the change to src/main/resources/rulesets/controversial.xml
and at best some tests?

See, for example:
https://github.com/phpmd/phpmd/pull/197/files

**Comment by silentx1981** [comment]
Hi @ravage84 

No I have forget the xml-file to commit and i also will try to write some tests.

**Comment by ravage84** [comment]
No problem. Take your time.

Are you Swiss by any chance?

**Comment by silentx1981** [comment]
Yes I'm Swiss, ja ich bin Schweizer

**Comment by ravage84** [comment]
Me, too.
I'm from Basel.
If you want, you can write me by e-mail or Skype on ravage@bluewin.ch

**Comment by silentx1981** [comment]
sorry for my new pull request. But i don't know how i can change my forked version.

**Comment by ravage84** [comment]
Closing as superseded by #363

**Pull request closed without merging**
