### PR TITLE
Add badges for the monthly and total downloads

### PR DESCRIPTION
**Pull request by tvbeek**
I thought it can give motivation to see the amount off downloads.

### CODE REVIEW

**Comment by ravage84** [comment]
Are they currently down?

I get invalid images, even on their website:

grafik

https://poser.pugx.org/

Totally broken?

**Comment by tvbeek** [comment]
> 
> 
> Are they currently down?
Yes, just after creating the PR 😞

**Comment by jakzal** [comment]
I'm not a fan of this kind of things, especially if they come from providers that tend to go down ;) 

However, here's an alternative: https://shields.io

**Comment by ravage84** [comment]
I've used the ones from shield.io in the past.

**Comment by tvbeek** [comment]
Then it is the question, do I change them to the shields.io version, keep it this way or close the PR?

**Pull request merged**
