### PR TITLE
Add TestMethodName rule

### LINKED ISSUE #251: Question: how to best make this extension to CamelCaseMethodName
In my projects, `camelCase` is required for method names. There however is an exception: tests. This is also allowed: `testGivenInvalidLanguage_exceptionIsThrown`.

The rules for this are:
- only applies to methods starting with "test" (in classes that end on "Test")
- only a single _ is allowed (though not required)
- the character after the _ should be lowercase
- the _ should separate the "given" and/or "when" from the "then" clause
  - 3 or more words (including "test") before the _
  - 2 or more words after the _

I'd like to implement this. Any advice on how to do this? Shall I create a new standalone rule, one that extends CamelCaseMethodName, or add an option to CamelCaseMethodName? And for the former two, would that be a welcome addition to this repo or not?

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes #251

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I'm having some trouble with making the rule only look at methods that are in test classes (see the one failing test). When I use the commented out code in `isTestMethod`, I get this error:

```
1) PHPMD\Rule\Controversial\TestMethodNameTest::testRuleDoesNotAddViolationForNonTestMethodNameTest
Argument 1 passed to PHPMD\Node\ASTNode::__construct() must be an instance of PDepend\Source\AST\ASTNode, instance of PDepend\Source\AST\ASTClass given, called in /home/j/workspace/phpmd/src/main/php/PHPMD/AbstractNode.php on line 110 and defined

/home/j/workspace/phpmd/src/main/php/PHPMD/Node/ASTNode.php:68
/home/j/workspace/phpmd/src/main/php/PHPMD/AbstractNode.php:110
/home/j/workspace/phpmd/src/main/php/PHPMD/Rule/Controversial/TestMethodName.php:84
/home/j/workspace/phpmd/src/main/php/PHPMD/Rule/Controversial/TestMethodName.php:72
/home/j/workspace/phpmd/src/test/php/PHPMD/Rule/Controversial/TestMethodNameTest.php:68
```
So it seems like I cannot call getParent, as then these tests blow up. Which makes me think it is really pointless the AST concern is bound to the actual rule logic in all the existing "unit" tests.

Any advice on how to implement this behaviour is greatly appreciated.

**Comment by JeroenDeDauw** [comment]
This error is caused because of a call to MethodNode::getParent, which is a derived method defined in PHPMD\AbstractNode, that constructs an PHPMD ASTNode given a ClassNode, while the PHPMD ASTNode expects a PDepend ASTNode, and ClassNode is not a PDepend ASTNode. Is that a mistake in the production code, or is something wrong with the test setup?

**Comment by JeroenDeDauw** [comment]
Still looking for input from the core devs here

**Comment by ravage84** [comment]
@JeroenDeDauw sorry for not getting back to you for sooooo long. 😿  🙇 

After having a second look at the whole thing, I have come to the conclusion, that this is way too specific for being a PHPMD rule.
That's why I'm going to close this.

Also, very sorry for wasting your time...

**Pull request closed without merging**
