### PR TITLE
Add allow-underscore option

### LINKED ISSUE #742: Add allow-underscore option
Since CamelCasePropertyName and CamelCaseMethodName already implement the `allow-underscore` and `allow-underscore-test` options it would be consistent to implement this option also for CamelCaseParameterName and CamelCaseVariableName.

It should be a quick addition which I could do in my spare time.

### PR DESCRIPTION
**Pull request by tuc0w**
Type: feature
Issue: Resolves #742 
Breaking change: no

This PR adds the allow-underscore option to CamelCaseParameterName and CamelCaseVariableName to make it consistent to the other controversial rules. It is used the same way it is used by the existing controversial rules.

### CODE REVIEW

**Comment by tuc0w** [comment]
> Nice PR,
> 
> You created the tests for CamelCaseVariableName but I miss the tests for CamelCaseParameterName. Can you add them?

Sure, I just didn't add them in first place because the whole CamelCaseParameterName tests are missing. Trying to add them today 👍

**Comment by tuc0w** [comment]
@tvbeek I just added the missing tests, should cover the cases now 🤔

**Comment by tuc0w** [comment]
No problem, thanks for the fast review!

**Comment by ravage84** [comment]
This replaced the stale PR https://github.com/phpmd/phpmd/pull/363

**Pull request merged**
