### PR TITLE
Adding a test with KWStyle for Travis CI

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by ravage84** [comment]
@RyDroid thanks for the suggestion.
For enforcing the style, I would prefer to use [Stickler CI](https://stickler-ci.com/) or alternatively the [Nitpick CI](https://nitpick-ci.com/).

I prefer the first because it is actively used for the [CakePHP framework](https://cakephp.org/), build by its lead developer Mark Story, which I personally know, too.

**Comment by ravage84** [comment]
Created #457

**Comment by RyDroid** [comment]
KWStyle is free/libre software and can be used localy. Stickler CI seems to be proprietary and online only. It is easier and faster to test locally. Moreover with a service, there is always the risk that it stops.

**Comment by ravage84** [comment]
Sure, by using services you always inherit some risks.
Nonetheless, I already have integrated Stickler CI now.

Plus KWStyle is not popular in the PHP community. Also it is not written in PHP.
While PHPCS is both and we already use it.
So I do not see the need for KWStyle.

By the way, have you seen https://github.com/phpmd/phpmd/commit/24ff5a9ec3308458db66da019901e4013a6ca4ee?

This way you can simply type ``composer cs-check`` and get the code checked against PSR-2.

**Comment by RyDroid** [comment]
Ok.
https://github.com/phpmd/phpmd/commit/24ff5a9ec3308458db66da019901e4013a6ca4ee looks like cool (but I never used composer, I am used to the C/C++ world with make and packages of my GNU/Linux distribution).

> Plus KWStyle is not popular in the PHP community.

That does not seem to me to be a good reason. Because by refusing to use it, you are partly responsible for his lack of popularity in the PHP community (it can look like a personal attack, but it is not the case, unfortunately I did not find an other way to write it).

> Also it is not written in PHP.

I can understand the problem of coherence (especially if the program has to be compiled or installed with a language specific tools, but here it is provided by Debian as a deb package). However with this argument, you rewrite each program in your own favorite language: a big lack of effort and time.

**Comment by ravage84** [comment]
> Plus KWStyle is not popular in the PHP community

It is not a reason, but a fact, I stated.

> That does not seem to me to be a good reason. Because by refusing to use it, you are partly responsible for his lack of popularity in the PHP community (it can look like a personal attack, but it is not the case, unfortunately I did not find an other way to write it).

That's OK, I got yoru message. 😼 

In the end, the PHP community has chosen or created its tools of choice over many years, just like C/C++ has, I assume.

One of those tools is [Composer](https://getcomposer.org/), which has revolutionized the way the PHP community can organize packages and dependencies. It's similar to NPM (inspired by, if I recall correctly).
The PHP community has moved away from system managed packages and dependencies for many good reasons.

As for code style checking in PHP there is already one ubiquitous tool: [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer). PHPMD already uses it and services like Scrutinizer CI and Travis CI either integrate it already or integrate with it well.

> However with this argument, you rewrite each program in your own favorite language: a big lack of effort and time.

While I do agree with you on this, this also allows to specialize and optimize a tool.
Since with PHPCS you only can check code style for languages a typical PHP web developer cares about (PHP, JavaScript and CSS), it does not get bloated but is the optimized tools for it.

If you are interseted in future contributing within the PHP community, I'd love to support you.

**Comment by RyDroid** [comment]
Ok. :-)

**Pull request closed without merging**
