### PR TITLE
WIP: Add empty catch block rule

### LINKED ISSUE #407: Detect empty catch blocks
Hello,

this is a feature request to detect empty catch blocks. I'm talking about this kind of practice:

``` php
<?php
try {
    some_function_call();
} catch (\Exception $e) {
    // do nothing, not even logging the exception
}
```

### PR DESCRIPTION
**Pull request by greg0ire**
Closes #407 

# Todo

- [ ] duplicate test cases for method / functions
- [ ] add a test with a comment inside a catch block

### CODE REVIEW

**Comment by greg0ire** [comment]
@ravage84 : here is my first draft, can you give me a review before I start doing more?

1. Is the naming good?
2. Are there more tests cases I need to add ?

**Comment by greg0ire** [comment]
ping @ravage84

**Comment by greg0ire** [comment]
pong @ravage84

**Comment by ravage84** [comment]
@greg0ire sorry, very busy right now.

**Comment by greg0ire** [comment]
No problem I'll wait… good luck with your business!

**Comment by kenguest** [comment]
I'm putting this here more as a reminder for myself than anything else, but if other people benefit, well.. that's a good thing?

PHP_CodeSniffer has a sniff/check for empty catch blocks, but enforces that there must be a comment inside that block to explain why nothing is being done with that caught exception.

phpcs --standard=Squiz --report=csv  --extensions=php --sniffs=Squiz.Commenting.EmptyCatchComment ~/test.php

Feel free to delete this if it's inappropriate for this forum...

**Comment by ravage84** [comment]
Superseded by #476

**Pull request closed without merging**
