### PR TITLE
Fixed undefined index referring

### LINKED ISSUE #816: Fatal error in AbstractLocalVariable
- PHPMD version: 2.9.0
- PHP Version: 7.4.9
- Installation type: composer
- Operating System / Distribution & Version: Debian 10.5

### Current Behavior
```
PHP Notice:  Undefined offset: 0 in /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php on line 271
PHP Fatal error:  Uncaught Error: Call to a member function isPassedByReference() on null in /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php:271
```

My phpmd-ruleset.xml:
```
<?xml version="1.0"?>
<ruleset name="Softline PHPMD rule set"
         xmlns="http://pmd.sf.net/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd"
         xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">

    <description>Softline Portal PHPMD rule set</description>

    <rule ref="rulesets/cleancode.xml/ElseExpression" />
    <rule ref="rulesets/cleancode.xml/DuplicatedArrayKey" />
    <rule ref="rulesets/cleancode.xml/UndefinedVariable" />

    <rule ref="rulesets/codesize.xml/CyclomaticComplexity">
        <properties>
            <property name="reportLevel" value="7" />
        </properties>
    </rule>
    <rule ref="rulesets/codesize.xml/NPathComplexity">
        <properties>
            <property name="minimum" value="40" />
        </properties>
    </rule>

    <rule ref="rulesets/codesize.xml/ExcessiveClassComplexity" />

    <rule ref="rulesets/controversial.xml/CamelCaseParameterName">
        <properties>
            <property name="allow-underscore" value="true" />
        </properties>
    </rule>
    <rule ref="rulesets/controversial.xml/CamelCaseVariableName">
        <properties>
            <property name="allow-underscore" value="true" />
        </properties>
    </rule>

    <rule ref="rulesets/design.xml">
        <exclude name="CouplingBetweenObjects" />
    </rule>

    <rule ref="rulesets/naming.xml">
        <exclude name="ShortVariable" />
        <exclude name="LongVariable" />
        <exclude name="ShortMethodName" />
    </rule>

</ruleset>
```

### PR DESCRIPTION
**Pull request by a-menshchikov**
Type: bugfix
Issue: Resolves #816
Breaking change: no

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Thank you @a-menshchikov did you find when/why (with which analyzed code) `$parameters[$argumentPosition]` is undefined?

**Comment by a-menshchikov** [comment]
@kylekatarnls error rising on the following code:
```
<?php

declare(strict_types=1);

namespace App\Controller\Api\admin\Settings\Language;

use App\Controller\Api\AbstractApiController;
use App\Entity\Language;
use App\Entity\User\Role;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

final class Activate extends AbstractApiController
{
    /**
     * @Rest\Patch("/settings/language/{id}/activate", name="language.activate")
     * @Rest\View(serializerGroups={"admin:language:status"})
     *
     * @IsGranted(Role::ADMIN)
     */
    public function __invoke(Language $language): View
    {
        $language->setActive(true);

        $this->flush($language);

        return $this->success($language);
    }
}
```
----
Full error output (with xdebug enabled):
```
PHP Notice:  Undefined offset: 0 in /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php on line 271
PHP Stack trace:
PHP   1. {main}() /usr/src/app/vendor/phpmd/phpmd/src/bin/phpmd:0
PHP   2. PHPMD\TextUI\Command::main($args = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/bin/phpmd:61
PHP   3. PHPMD\TextUI\Command->run($opts = *uninitialized*, $ruleSetFactory = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php:148
PHP   4. PHPMD\PHPMD->processFiles($inputPath = *uninitialized*, $ruleSets = *uninitialized*, $renderers = *uninitialized*, $ruleSetFactory = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php:103
PHP   5. PHPMD\Parser->parse($report = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php:192
PHP   6. PDepend\Engine->analyze() /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:95
PHP   7. PHPMD\Parser->close() /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php:357
PHP   8. PDepend\Source\AST\ASTNamespace->accept($visitor = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:148
PHP   9. PHPMD\Parser->visitNamespace($namespace = *uninitialized*) /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTNamespace.php:320
PHP  10. PDepend\Source\AST\ASTClass->accept($visitor = *uninitialized*) /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php:214
PHP  11. PHPMD\Parser->visitClass($node = *uninitialized*) /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTClass.php:196
PHP  12. PHPMD\Parser->visitClass($class = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:188
PHP  13. PDepend\Source\AST\ASTMethod->accept($visitor = *uninitialized*) /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php:110
PHP  14. PHPMD\Parser->visitMethod($node = *uninitialized*) /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTMethod.php:219
PHP  15. PHPMD\Parser->apply($node = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:234
PHP  16. PHPMD\RuleSet->apply($node = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:259
PHP  17. PHPMD\Rule\CleanCode\UndefinedVariable->apply($node = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSet.php:255
PHP  18. PHPMD\Rule\CleanCode\UndefinedVariable->isPassedByReference($variable = *uninitialized*) /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php:78
PHP Fatal error:  Uncaught Error: Call to a member function isPassedByReference() on null in /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php:271
Stack trace:
#0 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(78): PHPMD\Rule\AbstractLocalVariable->isPassedByReference()
#1 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSet.php(255): PHPMD\Rule\CleanCode\UndefinedVariable->apply()
#2 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(259): PHPMD\RuleSet->apply()
#3 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(234): PHPMD\Parser->apply()
#4 /usr/src/app/vendor/pdepend/pdepend/src/main/p in /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php on line 271
```
----
Maybe it will be useful: `$functionName` in AbstractLocalVariable::isPassedByReference() is equal "flush" and UndefinedVariable check `$language` variable on error.

**Comment by tvbeek** [comment]
@a-menshchikov thanks for the PR (and the issue) do you have the possibility to add a test to the PR? With that we have a verification that it is fixed and we don't destroy it in another release.

I assign this PR to you, but feel free to say if you need help creating the tests.

**Comment by a-menshchikov** [comment]
@tvbeek I think I need help with tests because at the moment I have no idea how to create it`s.

**Review by kylekatarnls — APPROVED** [review]

**Comment by kylekatarnls** [comment]
I just tried the same code chunk but get no error. I also tried with PDepend 2.7.1. I think we should merge this and #821, release the patch 2.9.1 to fix the error then take the time to understand why and how it happen to fix it properly.

**Review by tvbeek — APPROVED** [review]

**Comment by kylekatarnls** [comment]
I could reproduce the bug. I'll add the tests in a second PR.

**Comment by kylekatarnls** [comment]
For the record: the error happen if there is more arguments in call than in definition:

```php
function foo($a, $b)
{
}

foo($v1, $v2, $v3);
```

Or if the definition of the function/method couldn't not be found. I both situation, it would be fine IMO to consider by default the variable is not passed by reference.

**Comment by kylekatarnls** [comment]
Erratum: the actual trigger is the method name "flush". PHPMD tried to match the arguments with the `flush()` function of PHP to check arguments passed by reference. So it's a problem to detect `$this->` and understand that `flush` is a method and not a function.

**Comment by kylekatarnls** [comment]
Funny fact: PHPStorm seems to do the same mistake as it underlines `$undefined` in `$this->Xpreg_match('', '', $undefined)` but not in  `$this->preg_match('', '', $undefined)` .

**Comment by a-menshchikov** [comment]
@kylekatarnls `flush` method used from trait that imported in parent class:
```
    protected function flush(?object $entity = null): void
    {
        $this->getManager($entity)->flush();
    }
```

**Pull request merged**
