### PR TITLE
Allow unused foreach variables

### PR DESCRIPTION
**Pull request by ravage84**
Resolves https://github.com/phpmd/phpmd/issues/48

### CODE REVIEW

**Comment by marcelloh** [comment]
Just checked, but in the 2.5.0 this issue still exists (or has returned)
(or it's unclear to me, how this rule is configurated with a certain ruleset)

**Comment by ravage84** [comment]
@marcelloh then please crreate a new issue detailing a code example and your related config.

**Comment by mjac** [comment]
@marcelloh Fails for me too on a basic `foreach ($array as $index => $value)`, did you make a new issue?

**Comment by marcelloh** [comment]
No, i did not. This issue is about it, so why create a new exact the same one?

**Comment by ravage84** [comment]
@marcelloh this is not an issue, it is a pull request. Please don't misuse a PR for offloading your issue. Creata a new one. Thank you.

**Comment by marcelloh** [comment]
Sorry... I was wrong, but issue 48 is closed, and that should be reopened

**Comment by ravage84** [comment]
It's cleaner to open a new issue and to reference othe old one, nonetheless.  Reopening old issues again only increases the tail. In the end people get lost in (partly) outdated information.

**Pull request merged**
