### PR TITLE
#321 Inspection: missing class import

### PR DESCRIPTION
**Pull request by DmitryNaum**
#321 Inspection: missing class import

### CODE REVIEW

**Comment by DmitryNaum** [comment]
@ravage84 i have no any comments, i think all is ok 👍

**Comment by luckyraul** [comment]
These rule in default checks is nonsense.

**Comment by kylekatarnls** [comment]
Nope, add `use Exception;` if you use is a best practice. Using `\Exception` is a mess. If you have an other opinion, you can disable the rule but there is no doubt it has its place in default configuration.

**Comment by luckyraul** [comment]
Imports are created to reduce line length and filesize. To make code readable. 
Your changes oppose that. Use should be used only for long names, not for one level classes

**Comment by luckyraul** [comment]
And this release should not broke all tests as it not a major release

**Comment by kylekatarnls** [comment]
> Imports are created to reduce line length and filesize.

That is the role you give to them. Not an fact.

> And this release should not broke all tests as it not a major release

It broke your tests if you decide to pass tests with version ^2 of PHPMD, if you want no rule change, you can select a fixed version and prevent update. But we will certainly not release a major change for each new rule or rule change!

PHPMD should not be a dependency of your project but a dev-dependency: a developer helper tool. Up to you to configure it and to choose you want new rule and supports for your project.

PHPMD could not even break anything, it's not supposed to be ran in a production environment. You're talking about breaking CI tests, that's not breaking change regarding to SemVer. When SemVer mention BC, it's about actual regression in applications, not about testing procedures.

**Comment by kylekatarnls** [comment]
As per a PHP doc example:
```php
use ArrayObject;
```

I think you misunderstood what imports are for, and that's why you're confused by this rule.

Imports are about knowing immediately when reading a file, what is used in it.

Hope it helps you to understand.

**Comment by ravage84** [comment]
@luckyraul thank you for reaching out ot us. For the future, please don't piggybag PRs. Please, open a separate issue in which you reference the relevant PRsand issues.

> Imports are created to reduce line length and filesize. To make code readable.

Half true. Most of the time they make the file smaller (as in charachters) and that often leads to more readable code. But the character reduction is rather a by-product. The actual benefit of imports is dependency visibility. If you have a big list of imports, your class might do too much.

> And this release should not break all tests as it not a major release. But it is.

Even though we follow SemVer and this is a minor realese (no BC breakage), one should never blindly update his dependencies, even if it should be backwards compatible. But I agree to some extend that new rules can trip a CI build. To counter this. add a PHPMD configuration file, in which you manually select each rule. But even without configuration file, it should not break your build, it should make it only unstable, at best (depending how low you configured your violation threshold).

By the way PHPMD is no testing tool but a metrics tool and should under normal circumstances be used as such.

**Comment by luckyraul** [comment]
One level native classes and objects are not dependencies.  ```use Exception``` does not make code more readable and helps me to undestand that I have exception in this file.

We have our rules file. And we use cleancode ruleset. And now it breaks all CI test in once.

**Comment by ravage84** [comment]
> One level native classes and objects are not dependencies. 

I guess you mean global scope classes and functions. Again, it is wrong that these aren't the classes dependencies. Your code won't work, if the PHP guys decided to rip out some global functionality, so it is a dependency.

> And now it breaks all CI test in once.

I'm sorry to hear. Like I said, if PHPMD is used as metrics software, it should not break any build, it should rather downgrade it.
Thanks again for bringing this up. We might find a way in the future to ease integration of new rules, but I can't promise anything.

**Comment by kylekatarnls** [comment]
You should not blame PHPMD for the red light in your CI. Red lights are here to help you. It's a perfect opportunity to read https://www.php.net/manual/en/language.namespaces.importing.php and better understand what imports are really for.

It allows to question assumptions you took (such as filesize importance or "global classes are not dependencies") and decide: is it really true? Should I change my code to follow this recommend pattern (remember that by installing PHPMD, you requested recommendations) or customize my rules. Then you will make a choice with your team according to your needs or take the value of the new rule.

In both case, rather you take the rule or not it adds the value PHPMD is supposed to deliver by making you aware of rules that exist.

Maybe you have different expectations when using PHPMD. If so, we would be happy to hear about. You can open an issue, tell us about your need, argument about the result you wish when running PHPMD for your project, and we could see if we should converge or if we should better explain the purpose of the tool in our documentation.

**Comment by ravage84** [comment]
I've locked this conversation as everything necessary was said. We can continue in a separate, dedicated isuse on that.

**Pull request merged**
