### PR TITLE
Run PHPStan in CI

### PR DESCRIPTION
**Pull request by AJenbo**
Mostly copied from PDepend with a few adjustments for dependencies

### CODE REVIEW

**Comment by szepeviktor** [comment]
In docblocks and exceptions FQCN should be used.
For example the fix in `SARIFRenderer`
```php
        /** @var \PHPMD\RuleViolation $violation */
```

**Comment by AJenbo** [comment]
I'm not sure how this is relevant for this PR, but we actually settled on importing the classes rather then using FQN, see https://github.com/pdepend/pdepend/pull/587

**Comment by szepeviktor** [comment]
All right, all right.

**Comment by AJenbo** [comment]
Here is a breakdown of how many issues are left at each level of PHPStan:

2:  61
3:  20
4:  29
5:  42
6: 125
7:  60
8:  40
9:  25

All in all very few issues.

**Review by tvbeek — APPROVED** [review]

**Pull request merged**
