### PR TITLE
PHPCS Rules

### PR DESCRIPTION
**Pull request by hbaeumer**
use doctrine coding standard and compatibility checker

### CODE REVIEW

**Comment by kylekatarnls** [comment]
PHP < 7.1 is broken, consider using a range for now: `^2.0 || ^3.0`

**Comment by kylekatarnls** [comment]
@hbaeumer Branch updated with 3.x, it should now pass.

**Comment by ravage84** [comment]
@hbaeumer  could you please elaborate why you chose to propose the adoption of the Doctrine coding style? I think we haven't talked thoroughly about the whole coding standard stuff. So your proposal might be a bit premature.

**Comment by hbaeumer** [comment]
Yes it is premature and DRAFT
I am preparing here a possible list with sniffs.
Also, I will discuss the individual rules before they are implemented.

**Comment by ravage84** [comment]
Closing as this got stale and I think we should first talk about this more.

**Pull request closed without merging**
