### PR TITLE
Use common directory structure

### PR DESCRIPTION
**Pull request by szepeviktor**
Type: refactoring
Breaking change: no

1. Use common directory structure as seen in thousands of PHP packages
2. Use PSR-4 autoloader (namespace\\ = src/)

image

🤩

What do you think about it?
Is it worth to finish?

### CODE REVIEW

**Comment by AJenbo** [comment]
I like the cleaned up structure

**Comment by kylekatarnls** [comment]
This will conflict with all our open pull-requests :(

**Comment by szepeviktor** [comment]
@kylekatarnls This really an inspiration.
Please manage it the way you want.

**Comment by AJenbo** [comment]
I belive git is actually able to resolve most of that automatically... though maybe not github

**Comment by ravage84** [comment]
I think we should look into this once the current dust of changes has settled on the next major version.

Also, I would go one step beyond the "common directory structure as seen in thousands of PHP packages".
We can try to adhere to the [directory structure standard of PHP PDS](https://github.com/php-pds/skeleton).

**Comment by AJenbo** [comment]
@szepeviktor if you are still interested in doing this refactoring then I think now is a good time for it.

**Comment by szepeviktor** [comment]
All right, going in ...

**Comment by AJenbo** [comment]
Oh, it should be rebased on the 3.x branch just fyi. I can help look at it later in the week.

**Comment by AJenbo** [comment]
Ok, I rebased on 3.x and got PHPStan and a few other things working. There are still 12 tests that are currently failing, apparently they can't find the rulesets any longer, not sure what needs to change there right now so if anyone has time to look at it that would be helpful :)

**Comment by AJenbo** [comment]
There we go that should do it.

**Comment by szepeviktor** [comment]
There are a few remaining `src/main`-s

**Comment by AJenbo** [comment]
PHP 8.1 is currently failing in general, fixed here: https://github.com/phpmd/phpmd/pull/1202

**Comment by AJenbo** [comment]
> There are a few remaining src/main-s

Ok, I think I got them all this time, let me know if you find any other issues (i didn't check any of the other paths).

**Comment by AJenbo** [comment]
Looks like the build process was hard coded for the file structure, but we where planning to migrate away from it any way. This should now pass all tests, there still remains a bit of work in porting, or at least testing, the site deployment process.

**Review by AJenbo — APPROVED** [review]

**Review by kylekatarnls — APPROVED** [review]

**Comment by szepeviktor** [comment]
Finally. We are in `3.x` :)

**Comment by AJenbo** [comment]
Yeah and it was the last of the main goals planned for 3.0 so now we just need to evaluate the optional ones

**Comment by szepeviktor** [comment]
Here we have an old path:
https://github.com/phpmd/phpmd/blob/3.x/composer.json#L62

**Comment by AJenbo** [comment]
Thanks fixed in https://github.com/phpmd/phpmd/pull/1208 
Also I did the same restructuring for PDepend: https://github.com/pdepend/pdepend/pull/885

**Pull request merged**
