### PR TITLE
Add note about TooManyMethods' ignorepattern setting

### PR DESCRIPTION
**Pull request by ravage84**
Refs https://github.com/phpmd/phpmd/issues/248#issuecomment-76845398

### CODE REVIEW

**Comment by manuelpichler** [comment]
I just generate *.rst files from the ruleset *.xml files. So therefore we must add the ```ignorepattern``` property to the ```codesize.xml``` file and replace the current constant for ```get|set``` with a default value in our configuration.

**Comment by JeroenDeDauw** [comment]
Ah no! I saw this commit, incorporated the changes into mine, and then read the comment. Fail!

**Comment by JeroenDeDauw** [comment]
I've updated `codesize.xml` in #273

**Comment by ravage84** [comment]
Closing as we can discuss this in the new PR #273

**Pull request closed without merging**
