### PR TITLE
Move suppression from method to class level

### PR DESCRIPTION
**Pull request by brendanlawton**
Type: (bugfix / feature / refactoring / documentation update)  
Issue: Resolves #.. the corresponding issue for this PR (if exist)
Breaking change: yes/no (if yes explain why)

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Can you please fill the template of the description and explain the reason of this change.

Both method-level and class-level suppression are possible in theory and I would recommend to be as precise as possible when bypassing a rule. I personally use only method-level ones.

**Comment by brendanlawton** [comment]
Ah, I need to delete this then and open a bug fix then because the warning is not suppressed when I add it to a method but it goes away when added to class-level. Example:

Warning **not** suppressed:
`/**
 * @ApiResource()
 * @ODM\EmbeddedDocument
 *
 * @SuppressWarnings(PHPMD.LongVariable)
 */
class Affiliate
{
    /**
     * @ODM\Id(strategy="increment", type="integer")
     * @var int
     */
    private $id;

    /**
     * @Groups({"client:read", "client:update", "siteConfig:read", "siteConfig:write"})
     * @ODM\Field(type="string", nullable=true)
     * @var string|null
     */
    private $affiliateLink;

    public function getId(): int
    {
        return $this->id;
    }

    public function getAffiliateLink(): ?string
    {
        return $this->affiliateLink;
    }

    public function setAffiliateLink(?string $affiliateLink): void
    {
        $this->affiliateLink = $affiliateLink;
    }
}`

Warning suppressed
`class Affiliate
{
    /**
     * @ODM\Id(strategy="increment", type="integer")
     * @var int
     */
    private $id;

    /**
     * @ODM\Field(type="string", nullable=true)
     * @var string|null
     *
     * @SuppressWarnings(PHPMD.LongVariable)
     */
    private $affiliateLink;


    public function getId(): int
    {
        return $this->id;
    }

    public function getAffiliateLink(): ?string
    {
        return $this->affiliateLink;
    }

    public function setAffiliateLink(?string $affiliateLink): void
    {
        $this->affiliateLink = $affiliateLink;
    }
}`

**Comment by kylekatarnls** [comment]
OK, I see, suppression is possible on classes and methods, but probably not on properties (I never tried). So it's more likely a request for a new feature.

So the documentation could be improved to tell about what is know to work properly such as a mention:
> Annotation can either be added over methods or classes.

Rather than remove the method example with UnusedLocalVariable that actually works.

Then an other issue would be to handle the case of property annotations.

**Comment by brendanlawton** [comment]
Ah, of course. Good spot. Thank you.

**Pull request closed without merging**
